services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'


  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass

    ports:
      - '5432:5432'