server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/root
    username: root
    password: pass

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: health, env
  endpoint:
    health:
      show-details: always